-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 15:05:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupomania` DEFAULT CHARACTER SET utf8 ;
USE `groupomania` ;

-- -----------------------------------------------------
-- Table `groupomania`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(70) NULL,
  `contenu` LONGTEXT NULL,
  `court` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(70) NULL,
  `contenu` MEDIUMTEXT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `articles_id`),
  CONSTRAINT `fk_commentaires_articles`
    FOREIGN KEY (`articles_id`)
    REFERENCES `groupomania`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commentaires_articles_idx` ON `groupomania`.`commentaires` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `groupomania`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupomania`.`utilisateurs` (
  `id` INT NOT NULL,
  `login` VARCHAR(70) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `login_UNIQUE` ON `groupomania`.`utilisateurs` (`login` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
